//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVIen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string ID_NHANVIEN { get; set; }
        public string HOTENNV { get; set; }
        public string MATKHAU { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string HINHANH { get; set; }
        public string EMAIL { get; set; }
        public string GIOITINH { get; set; }
        public string ROLE { get; set; }
    }
}
