//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuVIen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUHANHKIEM
    {
        public string ID_HK { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<byte> DIEM { get; set; }
        public string LOIVIPHAM { get; set; }
        public string ID_DOCGIA { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
    }
}
